"""Leakage-safe stacking of factor and foundation-model forecasts.

This module tests a small second-stage cross-sectional forecaster inspired by
the asset-pricing machine-learning literature.  The first-stage forecasts are
generated by :mod:`src.foundation_research` and :mod:`src.deep_ml_research`.
At every month-end, their cross-sectional ranks become inputs to a regularized
Ridge model or a shallow LightGBM model.  The stacker is refit with an
expanding window using only signal dates strictly before the forecast date.

The raw forecast files are intentionally ignored by Git because they can be
large and depend on model weights.  Run the foundation and deep experiments
before this module.  This is an audit harness, not a live trading strategy or
a claim that pretrained models have an Indonesian equity edge.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import importlib.util
import json
from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

try:  # Support both ``python -m src.stacked_research`` and direct execution.
    from . import foundation_robustness, ml_research, research
except ImportError:  # pragma: no cover - direct CLI compatibility
    from src import foundation_robustness, ml_research, research


ROOT = Path(__file__).resolve().parents[1]
REPORT_DIR = ROOT / "reports"
DEFAULT_FOUNDATION_FORECASTS = REPORT_DIR / "foundation_model_forecasts.csv"
DEFAULT_DEEP_FORECASTS = REPORT_DIR / "deep_ml_forecasts.csv"
DEFAULT_START = "2021-01-01"
DEFAULT_END = "2026-08-11"
DEFAULT_TOP_K = 3
DEFAULT_COST_BPS = 25.0
DEFAULT_MIN_TRAIN_MONTHS = 12
DEFAULT_RIDGE_ALPHA = 10.0
DEFAULT_LIGHTGBM_ROUNDS = 100
BOOTSTRAP_SAMPLES = 5_000
BOOTSTRAP_BLOCK_LENGTH = 3
BOOTSTRAP_SEED = 20260812

# These are primitive forecasts.  Derived ensemble columns from the previous
# reports are deliberately excluded so that the stacker does not count the
# same information twice.
BASE_MODELS = (
    "existing_composite",
    "chronos",
    "timesfm",
    "kronos",
    "mlp_raw",
    "mlp_excess",
)
RANK_FEATURE_NAMES = tuple(f"{name}_rank" for name in BASE_MODELS)
STACK_FEATURE_NAMES = (*RANK_FEATURE_NAMES, "rank_mean", "rank_dispersion")
STACK_MODELS = (
    "stack_ridge_raw",
    "stack_ridge_excess",
    "stack_lightgbm_raw",
    "stack_lightgbm_excess",
    "stack_ridge_lgbm_50",
    "stack_base_ridge_50",
)
METRIC_PERIOD_ORDER = (
    "train_2021",
    "validation_2022_2023",
    "holdout_2024",
    "holdout_2025_2026",
    "full",
)


@dataclass(frozen=True)
class StackConfig:
    price_field: str
    start: str
    end: str
    top_k: int
    cost_bps: float
    min_train_months: int
    ridge_alpha: float
    lightgbm_rounds: int
    foundation_forecasts: Path
    deep_forecasts: Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--price-field", choices=("adjclose", "close"), default="adjclose")
    parser.add_argument("--start", default=DEFAULT_START)
    parser.add_argument("--end", default=DEFAULT_END)
    parser.add_argument("--top-k", type=int, default=DEFAULT_TOP_K)
    parser.add_argument("--cost-bps", type=float, default=DEFAULT_COST_BPS)
    parser.add_argument("--min-train-months", type=int, default=DEFAULT_MIN_TRAIN_MONTHS)
    parser.add_argument("--ridge-alpha", type=float, default=DEFAULT_RIDGE_ALPHA)
    parser.add_argument("--lightgbm-rounds", type=int, default=DEFAULT_LIGHTGBM_ROUNDS)
    parser.add_argument("--foundation-forecasts", type=Path, default=DEFAULT_FOUNDATION_FORECASTS)
    parser.add_argument("--deep-forecasts", type=Path, default=DEFAULT_DEEP_FORECASTS)
    parser.add_argument("--status", action="store_true")
    return parser.parse_args()


def package_status() -> dict[str, dict[str, Any]]:
    """Report optional dependencies without importing model packages."""
    return {
        "lightgbm": {
            "available": importlib.util.find_spec("lightgbm") is not None,
            "package": "lightgbm",
            "version": _version("lightgbm"),
            "use": "shallow fixed-round second-stage stacker",
        }
    }


def _version(package: str) -> str | None:
    try:
        return importlib.metadata.version(package)
    except importlib.metadata.PackageNotFoundError:
        return None


def _json_safe(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if isinstance(value, np.generic):
        return _json_safe(value.item())
    if isinstance(value, float) and not np.isfinite(value):
        return None
    return value


def _safe_nanmean(values: np.ndarray, axis: int) -> np.ndarray:
    """Return NaN for all-missing slices without noisy runtime warnings."""
    valid = np.isfinite(values)
    count = valid.sum(axis=axis)
    total = np.nansum(values, axis=axis)
    result = np.full(count.shape, np.nan, dtype=float)
    np.divide(total, count, out=result, where=count > 0)
    return result


def _read_forecast_file(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}. Run the foundation/deep research runners before stacking."
        )
    frame = pd.read_csv(path)
    required = {"model", "signal_date", "ticker", "forecast"}
    missing = sorted(required - set(frame.columns))
    if missing:
        raise ValueError(f"{path} is missing columns: {', '.join(missing)}")
    frame["signal_date"] = pd.to_datetime(frame["signal_date"])
    frame["forecast"] = pd.to_numeric(frame["forecast"], errors="coerce")
    if frame.duplicated(["model", "signal_date", "ticker"]).any():
        raise ValueError(f"{path} contains duplicate model/date/ticker forecasts")
    return frame


def _model_panels(frame: pd.DataFrame, models: tuple[str, ...]) -> dict[str, pd.DataFrame]:
    panels: dict[str, pd.DataFrame] = {}
    for model in models:
        subset = frame.loc[frame["model"].eq(model)]
        if subset.empty:
            raise ValueError(f"Forecast file does not contain required model {model!r}")
        panels[model] = (
            subset.pivot(index="signal_date", columns="ticker", values="forecast")
            .sort_index()
            .sort_index(axis=1)
            .astype(float)
        )
    return panels


def load_forecast_panels(
    foundation_path: Path,
    deep_path: Path,
    tickers: list[str],
) -> dict[str, pd.DataFrame]:
    """Load and align primitive forecast panels from the two prior runs."""
    foundation = _model_panels(_read_forecast_file(foundation_path), BASE_MODELS[:4])
    deep = _model_panels(_read_forecast_file(deep_path), BASE_MODELS[4:])
    panels = {**foundation, **deep}
    common_dates = pd.DatetimeIndex(
        sorted(set.intersection(*(set(panel.index) for panel in panels.values())))
    )
    common_tickers = sorted(
        set(tickers).intersection(
            set.intersection(*(set(panel.columns) for panel in panels.values()))
        )
    )
    if common_dates.empty or not common_tickers:
        raise ValueError("No common dates and tickers exist across the forecast files")
    aligned = {
        model: panel.reindex(index=common_dates, columns=common_tickers)
        for model, panel in panels.items()
    }
    # Missing symbol-month forecasts are retained.  Learned stackers use
    # complete rows only; rank ensembles can still use the available models.
    # This is preferable to imputing a model's prediction or silently
    # shrinking the universe differently for each experiment.
    return aligned


def build_stack_panel(
    panels: dict[str, pd.DataFrame],
    features: dict[str, pd.DataFrame | pd.Series],
    start: str,
    end: str,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, pd.DataFrame]]:
    """Build rank features and next-month targets for the stacker."""
    if tuple(panels) != BASE_MODELS:
        panels = {model: panels[model] for model in BASE_MODELS}
    rank_panels = {
        model: panel.rank(axis=1, pct=True, method="average")
        for model, panel in panels.items()
    }
    common_dates = pd.DatetimeIndex(
        sorted(set.intersection(*(set(panel.index) for panel in rank_panels.values())))
    )
    common_dates = common_dates[(common_dates >= pd.Timestamp(start)) & (common_dates <= pd.Timestamp(end))]
    tickers = sorted(set.intersection(*(set(panel.columns) for panel in rank_panels.values())))
    monthly_returns = features["monthly_returns"]
    benchmark_returns = features["benchmark_returns"]
    assert isinstance(monthly_returns, pd.DataFrame)
    assert isinstance(benchmark_returns, pd.Series)
    target = monthly_returns.shift(-1)
    benchmark_next = benchmark_returns.shift(-1)
    common_dates = common_dates.intersection(target.index)
    if common_dates.empty or not tickers:
        raise ValueError("No aligned signal dates with next-month targets")

    rank_values = np.stack(
        [rank_panels[model].reindex(index=common_dates, columns=tickers).to_numpy() for model in BASE_MODELS],
        axis=2,
    )
    rank_mean = _safe_nanmean(rank_values, axis=2)
    centered = rank_values - rank_mean[:, :, None]
    rank_dispersion = np.sqrt(_safe_nanmean(centered * centered, axis=2))
    rows: list[pd.DataFrame] = []
    for date_position, signal_date in enumerate(common_dates):
        frame = pd.DataFrame({"ticker": tickers})
        for model_position, model in enumerate(BASE_MODELS):
            frame[f"{model}_rank"] = rank_values[date_position, :, model_position]
        frame["rank_mean"] = rank_mean[date_position]
        frame["rank_dispersion"] = rank_dispersion[date_position]
        frame["target"] = target.reindex(index=[signal_date], columns=tickers).iloc[0].to_numpy()
        benchmark_value = benchmark_next.get(signal_date, np.nan)
        frame["target_excess"] = frame["target"] - benchmark_value
        frame["signal_date"] = signal_date
        rows.append(frame)
    panel = pd.concat(rows, ignore_index=True)
    panel["signal_date"] = pd.to_datetime(panel["signal_date"])
    base_ensemble = pd.DataFrame(
        rank_mean,
        index=common_dates,
        columns=tickers,
    )
    return panel, base_ensemble, rank_panels


def _training_and_current(
    panel: pd.DataFrame,
    signal_date: pd.Timestamp,
    target_column: str,
    min_train_months: int,
) -> tuple[pd.DataFrame, pd.DataFrame] | None:
    required = [*STACK_FEATURE_NAMES, target_column]
    train = panel.loc[panel["signal_date"] < signal_date].dropna(subset=required)
    current = panel.loc[panel["signal_date"].eq(signal_date)].dropna(subset=STACK_FEATURE_NAMES)
    if train["signal_date"].nunique() < min_train_months or current.empty:
        return None
    return train, current


def _winsorize(values: np.ndarray) -> np.ndarray:
    return ml_research._winsorize(values)


def _ridge_fit_predict(
    train: pd.DataFrame,
    current: pd.DataFrame,
    target_column: str,
    alpha: float,
) -> pd.Series:
    x_train = train.loc[:, STACK_FEATURE_NAMES].to_numpy(dtype=float)
    y_train = _winsorize(train[target_column].to_numpy(dtype=float))
    x_current = current.loc[:, STACK_FEATURE_NAMES].to_numpy(dtype=float)
    mean = x_train.mean(axis=0)
    scale = x_train.std(axis=0)
    scale[scale < 1e-9] = 1.0
    z_train = (x_train - mean) / scale
    z_current = (x_current - mean) / scale
    system = z_train.T @ z_train + alpha * np.eye(z_train.shape[1])
    coefficients = np.linalg.solve(system, z_train.T @ (y_train - y_train.mean()))
    prediction = y_train.mean() + z_current @ coefficients
    return pd.Series(prediction, index=current["ticker"].to_numpy())


def _lightgbm_fit_predict(
    train: pd.DataFrame,
    current: pd.DataFrame,
    target_column: str,
    rounds: int,
) -> pd.Series:
    try:
        import lightgbm as lgb
    except ImportError as exc:  # pragma: no cover - optional environment
        raise RuntimeError("LightGBM is not installed; install requirements-ml.txt") from exc
    x_train = train.loc[:, STACK_FEATURE_NAMES].to_numpy(dtype=float)
    x_current = current.loc[:, STACK_FEATURE_NAMES].to_numpy(dtype=float)
    dataset = lgb.Dataset(
        x_train,
        label=_winsorize(train[target_column].to_numpy(dtype=float)),
        feature_name=list(STACK_FEATURE_NAMES),
        free_raw_data=True,
    )
    model = lgb.train(
        {
            "objective": "regression",
            "learning_rate": 0.03,
            "num_leaves": 7,
            "max_depth": 3,
            "min_data_in_leaf": 30,
            "lambda_l1": 1.0,
            "lambda_l2": 20.0,
            "feature_fraction": 0.8,
            "bagging_fraction": 0.8,
            "bagging_freq": 1,
            "seed": 42,
            "feature_fraction_seed": 42,
            "bagging_seed": 42,
            "data_random_seed": 42,
            "deterministic": True,
            "force_col_wise": True,
            "verbosity": -1,
        },
        dataset,
        num_boost_round=rounds,
    )
    return pd.Series(model.predict(x_current), index=current["ticker"].to_numpy())


def walk_forward_stacker(
    panel: pd.DataFrame,
    model: str,
    target_column: str,
    min_train_months: int = DEFAULT_MIN_TRAIN_MONTHS,
    ridge_alpha: float = DEFAULT_RIDGE_ALPHA,
    lightgbm_rounds: int = DEFAULT_LIGHTGBM_ROUNDS,
) -> tuple[pd.DataFrame, pd.Series]:
    """Fit a stacker at each date using only earlier signal months."""
    if model not in {"ridge", "lightgbm"}:
        raise ValueError(f"Unsupported stacker model: {model}")
    tickers = sorted(panel["ticker"].dropna().unique())
    signal_dates = pd.DatetimeIndex(sorted(panel["signal_date"].unique()))
    predictions = pd.DataFrame(index=signal_dates, columns=tickers, dtype=float)
    training_counts = pd.Series(index=signal_dates, dtype=float)
    for signal_date in signal_dates:
        prepared = _training_and_current(panel, pd.Timestamp(signal_date), target_column, min_train_months)
        if prepared is None:
            continue
        train, current = prepared
        if model == "ridge":
            predicted = _ridge_fit_predict(train, current, target_column, ridge_alpha)
        else:
            predicted = _lightgbm_fit_predict(train, current, target_column, lightgbm_rounds)
        predictions.loc[signal_date, predicted.index] = predicted.to_numpy()
        training_counts.loc[signal_date] = len(train)
    return predictions, training_counts


def rank_blend(*predictions: pd.DataFrame) -> pd.DataFrame:
    """Average available cross-sectional ranks without filling missing models."""
    if not predictions:
        raise ValueError("At least one prediction panel is required")
    index = predictions[0].index
    columns = predictions[0].columns
    ranked = [ml_research.rank_predictions(panel.reindex(index=index, columns=columns)) for panel in predictions]
    values = np.stack([panel.to_numpy(dtype=float) for panel in ranked], axis=2)
    blended = _safe_nanmean(values, axis=2)
    all_missing = np.all(~np.isfinite(values), axis=2)
    blended[all_missing] = np.nan
    return pd.DataFrame(blended, index=index, columns=columns)


def _slice_features(
    features: dict[str, pd.DataFrame | pd.Series],
    start: str,
    end: str,
) -> dict[str, pd.DataFrame | pd.Series]:
    result: dict[str, pd.DataFrame | pd.Series] = {}
    start_date = pd.Timestamp(start)
    end_date = pd.Timestamp(end)
    for name, value in features.items():
        if isinstance(value.index, pd.DatetimeIndex):
            result[name] = value.loc[(value.index >= start_date) & (value.index <= end_date)]
        else:  # pragma: no cover - current research inputs are date-indexed
            result[name] = value
    return result


def _metric_periods(config: StackConfig) -> dict[str, tuple[str, str]]:
    return {
        "train_2021": ("2021-01-01", "2021-12-31"),
        "validation_2022_2023": ("2022-01-01", "2023-12-31"),
        "holdout_2024": ("2024-01-01", "2024-12-31"),
        "holdout_2025_2026": ("2025-01-01", config.end),
        "full": (config.start, config.end),
    }


def _metrics(simulation: pd.DataFrame, config: StackConfig) -> dict[str, dict[str, Any]]:
    return {
        label: ml_research.period_metrics(simulation, start, end, label)
        for label, (start, end) in _metric_periods(config).items()
    }


def _format_metric(value: Any) -> str:
    if value is None or (isinstance(value, (float, np.floating)) and not np.isfinite(value)):
        return "—"
    if isinstance(value, (float, np.floating)):
        return f"{float(value):.4f}"
    return str(value)


def _metrics_table(metrics: dict[str, dict[str, dict[str, Any]]]) -> str:
    columns = (
        "model",
        "period",
        "months",
        "excess_cagr",
        "strategy_sharpe_rf0",
        "strategy_max_drawdown",
        "average_monthly_turnover",
    )
    lines = [
        "| " + " | ".join(columns) + " |",
        "|" + "|".join("---" for _ in columns) + "|",
    ]
    for model, model_metrics in metrics.items():
        for period in METRIC_PERIOD_ORDER:
            row = model_metrics.get(period, {})
            lines.append(
                "| "
                + " | ".join(
                    [
                        model,
                        period,
                        str(row.get("months", 0)),
                        _format_metric(row.get("excess_cagr")),
                        _format_metric(row.get("strategy_sharpe_rf0")),
                        _format_metric(row.get("strategy_max_drawdown")),
                        _format_metric(row.get("average_monthly_turnover")),
                    ]
                )
                + " |"
            )
    return "\n".join(lines)


def _block_bootstrap_active(
    candidate: pd.DataFrame,
    comparator: pd.DataFrame,
    start: str,
    end: str,
    seed: int,
    samples: int = BOOTSTRAP_SAMPLES,
    block_length: int = BOOTSTRAP_BLOCK_LENGTH,
) -> dict[str, Any]:
    """Bootstrap paired monthly active returns with circular blocks."""
    frame = pd.concat(
        [candidate["strategy_return"], comparator["strategy_return"]],
        axis=1,
        keys=("candidate", "comparator"),
    ).loc[start:end].dropna()
    difference = (frame["candidate"] - frame["comparator"]).to_numpy(dtype=float)
    if len(difference) < block_length:
        return {
            "months": int(len(difference)),
            "annualized_active_mean": np.nan,
            "ci_lower": np.nan,
            "ci_median": np.nan,
            "ci_upper": np.nan,
            "positive_probability": np.nan,
            "samples": samples,
            "block_length": block_length,
        }
    rng = np.random.default_rng(seed)
    block_count = int(np.ceil(len(difference) / block_length))
    starts = rng.integers(0, len(difference), size=(samples, block_count))
    offsets = np.arange(block_length)[None, None, :]
    indices = (starts[:, :, None] + offsets).reshape(samples, -1)[:, : len(difference)]
    indices %= len(difference)
    annualized = difference[indices].mean(axis=1) * 12.0
    quantiles = np.quantile(annualized, [0.025, 0.50, 0.975])
    return {
        "months": int(len(difference)),
        "annualized_active_mean": float(difference.mean() * 12.0),
        "ci_lower": float(quantiles[0]),
        "ci_median": float(quantiles[1]),
        "ci_upper": float(quantiles[2]),
        "positive_probability": float(np.mean(annualized > 0.0)),
        "samples": samples,
        "block_length": block_length,
    }


def _active_start(predictions: pd.DataFrame) -> pd.Timestamp | None:
    active = predictions.notna().any(axis=1)
    return pd.Timestamp(active[active].index[0]) if active.any() else None


def _render_rolling_summary(summary: pd.DataFrame) -> str:
    columns = (
        "model",
        "cost_bps",
        "windows",
        "median_sharpe",
        "positive_excess_fraction",
        "worst_excess_cagr",
        "median_turnover",
    )
    if summary.empty:
        return "_No rolling diagnostics available._"
    lines = [
        "| " + " | ".join(columns) + " |",
        "|" + "|".join("---" for _ in columns) + "|",
    ]
    for _, row in summary.sort_values(["cost_bps", "model"]).iterrows():
        lines.append(
            "| "
            + " | ".join(
                _format_metric(row.get(column)) if column not in {"model", "cost_bps", "windows"} else str(row.get(column))
                for column in columns
            )
            + " |"
        )
    return "\n".join(lines)


def _render_bootstrap(bootstrap: pd.DataFrame) -> str:
    columns = (
        "model",
        "months",
        "market_active_annualized_mean",
        "market_ci",
        "market_positive_probability",
        "control_active_annualized_mean",
        "control_ci",
    )
    if bootstrap.empty:
        return "_No bootstrap diagnostics available._"
    lines = [
        "| " + " | ".join(columns) + " |",
        "|" + "|".join("---" for _ in columns) + "|",
    ]
    for _, row in bootstrap.iterrows():
        market_ci = f"[{row['market_ci_lower']:.4f}, {row['market_ci_upper']:.4f}]"
        control_ci = f"[{row['control_ci_lower']:.4f}, {row['control_ci_upper']:.4f}]"
        lines.append(
            f"| {row['model']} | {int(row['months'])} | {_format_metric(row['market_active_annualized_mean'])} | "
            f"{market_ci} | {_format_metric(row['market_positive_probability'])} | "
            f"{_format_metric(row['control_active_annualized_mean'])} | {control_ci} |"
        )
    return "\n".join(lines)


def _gate_candidate(
    model: str,
    metrics: dict[str, dict[str, Any]],
    baseline_metrics: dict[str, dict[str, Any]],
    robustness: pd.DataFrame,
    rolling_summary: pd.DataFrame,
    bootstrap: pd.DataFrame,
) -> tuple[bool, list[str]]:
    reasons: list[str] = []
    validation_excess = metrics.get("validation_2022_2023", {}).get("excess_cagr", np.nan)
    baseline_excess = baseline_metrics.get("validation_2022_2023", {}).get("excess_cagr", np.nan)
    if not np.isfinite(validation_excess) or not np.isfinite(baseline_excess) or validation_excess <= baseline_excess:
        reasons.append("validation excess CAGR does not beat the existing composite")
    for period in ("holdout_2024", "holdout_2025_2026"):
        rows = robustness.loc[robustness["model"].eq(model) & robustness["period"].eq(period)]
        for cost in (25.0, 100.0):
            row = rows.loc[np.isclose(rows["cost_bps"], cost)]
            excess = row.iloc[0]["excess_cagr"] if not row.empty else np.nan
            if not np.isfinite(excess) or excess <= 0.0:
                reasons.append(f"excess CAGR is not positive in {period} at {int(cost)} bps")
    rolling = rolling_summary.loc[
        rolling_summary["model"].eq(model) & np.isclose(rolling_summary["cost_bps"], 25.0)
    ]
    positive_fraction = rolling.iloc[0]["positive_excess_fraction"] if not rolling.empty else np.nan
    if not np.isfinite(positive_fraction) or positive_fraction < 0.60:
        reasons.append("fewer than 60% of trailing 12-month windows have positive excess CAGR")
    boot = bootstrap.loc[bootstrap["model"].eq(model)]
    lower = boot.iloc[0]["market_ci_lower"] if not boot.empty else np.nan
    if not np.isfinite(lower) or lower <= 0.0:
        reasons.append("95% block-bootstrap lower CI for active return versus IHSG is not above zero")
    return not reasons, reasons


def write_report(
    config: StackConfig,
    panels: dict[str, pd.DataFrame],
    prediction_panels: dict[str, pd.DataFrame],
    simulations: dict[str, pd.DataFrame],
    metrics: dict[str, dict[str, dict[str, Any]]],
    training_rows: pd.DataFrame,
    errors: dict[str, str],
    evaluation_features: dict[str, pd.DataFrame | pd.Series],
) -> tuple[Path, Path]:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    robustness = foundation_robustness.build_cost_and_block_diagnostics(
        prediction_panels,
        evaluation_features,
        config.top_k,
    )
    rolling = foundation_robustness.build_rolling_diagnostics(
        prediction_panels,
        evaluation_features,
        config.top_k,
        cost_bps=config.cost_bps,
    )
    rolling_summary = foundation_robustness.summarize_rolling_diagnostics(rolling)
    existing_simulation = simulations["existing_composite"]
    market_comparator = existing_simulation[["benchmark_return"]].rename(
        columns={"benchmark_return": "strategy_return"}
    )
    bootstrap_rows: list[dict[str, Any]] = []
    for model, simulation in simulations.items():
        if model == "existing_composite":
            continue
        market = _block_bootstrap_active(
            simulation,
            market_comparator,
            "2024-01-01",
            config.end,
            BOOTSTRAP_SEED,
        )
        control = _block_bootstrap_active(
            simulation,
            existing_simulation,
            "2024-01-01",
            config.end,
            BOOTSTRAP_SEED,
        )
        bootstrap_rows.append(
            {
                "model": model,
                "months": market["months"],
                "market_active_annualized_mean": market["annualized_active_mean"],
                "market_ci_lower": market["ci_lower"],
                "market_ci_median": market["ci_median"],
                "market_ci_upper": market["ci_upper"],
                "market_positive_probability": market["positive_probability"],
                "control_active_annualized_mean": control["annualized_active_mean"],
                "control_ci_lower": control["ci_lower"],
                "control_ci_median": control["ci_median"],
                "control_ci_upper": control["ci_upper"],
                "control_positive_probability": control["positive_probability"],
                "samples": BOOTSTRAP_SAMPLES,
                "block_length": BOOTSTRAP_BLOCK_LENGTH,
            }
        )
    bootstrap = pd.DataFrame(bootstrap_rows)
    gates: dict[str, dict[str, Any]] = {}
    for model in prediction_panels:
        if model == "existing_composite":
            continue
        passed, reasons = _gate_candidate(
            model,
            metrics[model],
            metrics["existing_composite"],
            robustness,
            rolling_summary,
            bootstrap,
        )
        gates[model] = {"passed": passed, "reasons": reasons}
    candidates = [model for model in prediction_panels if model != "existing_composite"]
    validation_winner = max(
        candidates,
        key=lambda model: (
            metrics[model].get("validation_2022_2023", {}).get("strategy_sharpe_rf0", -np.inf),
            metrics[model].get("validation_2022_2023", {}).get("excess_cagr", -np.inf),
        ),
    ) if candidates else None
    preferred = validation_winner if validation_winner and gates[validation_winner]["passed"] else None

    metrics_rows = []
    for model, model_metrics in metrics.items():
        for period, values in model_metrics.items():
            metrics_rows.append({"model": model, **values})
    metrics_path = REPORT_DIR / "stacked_model_metrics.csv"
    pd.DataFrame(metrics_rows).to_csv(metrics_path, index=False)
    robustness_path = REPORT_DIR / "stacked_model_robustness.csv"
    rolling_path = REPORT_DIR / "stacked_model_rolling.csv"
    rolling_summary_path = REPORT_DIR / "stacked_model_rolling_summary.csv"
    bootstrap_path = REPORT_DIR / "stacked_model_bootstrap.csv"
    training_path = REPORT_DIR / "stacked_model_training.csv"
    robustness.to_csv(robustness_path, index=False)
    rolling.to_csv(rolling_path, index=False)
    rolling_summary.to_csv(rolling_summary_path, index=False)
    bootstrap.to_csv(bootstrap_path, index=False)
    training_rows.to_csv(training_path, index=False)

    forecast_rows: list[pd.DataFrame] = []
    for model, panel in prediction_panels.items():
        values = panel.to_numpy(dtype=float)
        row_indices, column_indices = np.where(np.isfinite(values))
        if len(row_indices):
            model_rows = pd.DataFrame(
                {
                    "signal_date": panel.index.to_numpy()[row_indices],
                    "ticker": panel.columns.to_numpy()[column_indices],
                    "forecast": values[row_indices, column_indices],
                }
            )
            model_rows.insert(0, "model", model)
            forecast_rows.append(model_rows)
    forecasts_path = REPORT_DIR / "stacked_model_forecasts.csv"
    if forecast_rows:
        pd.concat(forecast_rows, ignore_index=True).to_csv(forecasts_path, index=False)

    gate_lines = []
    for model in candidates:
        status = "passes" if gates[model]["passed"] else "rejects"
        reasons = "; ".join(gates[model]["reasons"]) if gates[model]["reasons"] else "all fixed audit checks passed"
        gate_lines.append(f"- **{model}:** {status} the fixed audit gate ({reasons}).")
    model_source_lines = "\n".join(
        f"- `{model}`: `{panels[model].shape[0]}` signal months × `{panels[model].shape[1]}` tickers; "
        f"`{int(panels[model].isna().sum().sum())}` missing symbol-month rows retained"
        for model in BASE_MODELS
    )
    report = f"""# Forecast-stacking research

Run date: {date.today().isoformat()}<br>
Research universe: `data/universe_idx30_2026-08.csv`<br>
Signal convention: first-stage forecasts and ranks use information available through completed month-end `t`; the stacker predicts and trades the next completed month's return<br>
Price field: `{config.price_field}`; top K: `{config.top_k}`; cost: `{config.cost_bps:.1f}` bps one-way<br>
Common first-stage coverage: `{min(panel.index.min() for panel in panels.values()).date()}` through `{max(panel.index.max() for panel in panels.values()).date()}`<br>
Stacker evaluation starts after the `{config.min_train_months}`-signal-month expanding-window warm-up.

## Research basis

- Gu, Kelly, and Xiu compare regularized linear models, trees, and neural networks for cross-sectional asset-pricing prediction and emphasize nonlinear interactions among momentum, liquidity, and volatility: [NBER Working Paper 25398](https://www.nber.org/papers/w25398).
- Campbell and Thompson stress that return predictors must be judged out of sample and can fail for long periods even when they have in-sample relationships: [NBER Working Paper 11468](https://www.nber.org/papers/w11468).

This is a stacking extension of that cross-sectional setup, not a literal reproduction of either paper. The papers motivate testing nonlinear interactions and strict out-of-sample evaluation; they do not validate these pretrained models or this Indonesian universe.

## First-stage inputs

{model_source_lines}

The stacker uses only primitive rank inputs: existing composite, Chronos, TimesFM, Kronos, raw-return factor MLP, and excess-return factor MLP. Each rank is computed across stocks at the same signal date. Two fixed summary inputs are added: mean rank (agreement) and cross-model rank dispersion (disagreement). Derived foundation/deep ensemble outputs are excluded to avoid duplicate information.

## Leakage controls and fixed models

- Every forecast month `t` is fit using rows with `signal_date < t`; the current month's target is never in its training set. Learned stackers use complete feature rows only; missing model forecasts are not imputed.
- Ridge uses training-only standardization, 1%/99% training-target winsorization, and fixed alpha `{config.ridge_alpha:g}`.
- LightGBM is a shallow fixed-round model: 7 leaves, depth 3, minimum leaf size 30, L1/L2 regularization, fixed seeds, and `{config.lightgbm_rounds}` boosting rounds. Its API follows the official `lgb.Dataset`/`lgb.train` interface.
- `forecast_rank_ensemble` is the equal average of the six base ranks. `stack_ridge_lgbm_50` averages the Ridge and LightGBM rank forecasts; `stack_base_ridge_50` averages the base-rank ensemble and Ridge rank forecast. These are fixed 50/50 combinations; no holdout-selected weight is used.
- Validation is 2022–2023. The 2024 and 2025–2026 blocks are holdouts and are not used to choose a model or parameter.

## Results

{_metrics_table(metrics)}

The validation winner among stacker candidates was **{validation_winner or 'none'}** under the pre-declared rule of highest validation Sharpe, then excess CAGR. The existing composite remains the control. A candidate is only called historically audit-passing if it beats the control in validation, has positive excess CAGR in both fixed holdout blocks at both 25 and 100 bps, is positive in at least 60% of rolling 12-month windows, and has a positive 95% circular three-month block-bootstrap lower confidence bound versus IHSG.

The 2021 rows are the stacker's expanding-window warm-up, so learned candidates have no traded evaluation months there. The comparable evaluation begins in January 2022 after 12 prior signal months.

## Fixed audit gate

{chr(10).join(gate_lines) if gate_lines else '_No stacker candidates completed._'}

Preferred causal research candidate: **{preferred or 'none'}**. This preference is based on the validation winner surviving the pre-declared audit, not on selecting the best holdout return. Even a passing candidate is not promoted to the web app or live trading because the current IDX30 history has survivorship/index-membership bias and the paired control interval can still include zero.

## Paired block bootstrap

The 2024–2026 comparison resamples paired three-month circular blocks 5,000 times. Market columns compare a candidate with IHSG; control columns compare it with the existing composite. These are uncertainty diagnostics for this sample, not a statistical guarantee under a new universe or regime.

{_render_bootstrap(bootstrap)}

## Stability and costs

The full cost/block table is in `reports/stacked_model_robustness.csv`; rolling windows are in `reports/stacked_model_rolling.csv` and `reports/stacked_model_rolling_summary.csv`.

{_render_rolling_summary(rolling_summary.loc[np.isclose(rolling_summary["cost_bps"], config.cost_bps)] if not rolling_summary.empty else rolling_summary)}

## Runtime and limitations

LightGBM status: `{package_status()['lightgbm']['available']}`; version: `{package_status()['lightgbm']['version'] or '—'}`.<br>
Errors/skips: `{json.dumps(errors, sort_keys=True)}`.

- The first-stage files were produced by earlier rolling runs; rerun them when changing model IDs, context length, price field, or data dates.
- The 30-name panel is a current-universe snapshot, so historical constituents and delisted stocks are missing. The all-listed catalog in the app is not yet a point-in-time research panel.
- Yahoo Finance data omit or simplify exchange-specific limits, suspensions, taxes, spreads, market impact, and execution timing.
- A model that passes this fixed historical gate may still be overfit to the finite panel. It is not investment advice and does not guarantee beating IHSG.

## Reproduction

```bash
python3 -m src.foundation_research --models all --start {config.start} --end {config.end} --kronos-repo /tmp/Kronos
PYTHONPATH=$PWD /tmp/beat-market-deep/bin/python -m src.deep_ml_research
PYTHONPATH=$PWD /tmp/beat-market-ml-venv/bin/python -m src.stacked_research \
  --start {config.start} --end {config.end} --min-train-months {config.min_train_months}
```

The raw stack forecasts are written locally to ignored `reports/stacked_model_forecasts.csv`. Committed audit artifacts are `reports/stacked_model_findings.md`, `reports/stacked_model_metrics.csv`, `reports/stacked_model_robustness.csv`, `reports/stacked_model_rolling_summary.csv`, `reports/stacked_model_bootstrap.csv`, and `reports/stacked_model_training.csv`.
"""
    report_path = REPORT_DIR / "stacked_model_findings.md"
    report_path.write_text(report, encoding="utf-8")
    summary_path = REPORT_DIR / "stacked_model_summary.json"
    summary_path.write_text(
        json.dumps(
            _json_safe(
                {
                    "run_at_utc": datetime.now(timezone.utc).isoformat(),
                    "config": {
                        **{key: str(value) if isinstance(value, Path) else value for key, value in config.__dict__.items()},
                    },
                    "base_models": list(BASE_MODELS),
                    "stack_features": list(STACK_FEATURE_NAMES),
                    "models": metrics,
                    "validation_winner": validation_winner,
                    "preferred_research_candidate": preferred,
                    "gates": gates,
                    "errors": errors,
                    "bootstrap": bootstrap.to_dict(orient="records"),
                }
            ),
            indent=2,
            allow_nan=False,
        ),
        encoding="utf-8",
    )
    return report_path, metrics_path


def run(config: StackConfig) -> dict[str, dict[str, Any]]:
    if not 1 <= config.top_k <= 30:
        raise ValueError("top_k must be between 1 and 30")
    if config.cost_bps < 0.0:
        raise ValueError("cost_bps must be non-negative")
    if config.min_train_months < 6:
        raise ValueError("min_train_months must be at least six")
    if config.ridge_alpha <= 0.0 or config.lightgbm_rounds < 1:
        raise ValueError("ridge_alpha must be positive and lightgbm_rounds must be positive")

    prices, volumes, tickers = research.load_prices(config.price_field)
    prices = prices.loc[prices.index <= config.end]
    volumes = volumes.reindex(prices.index)
    features = research.make_features(prices, volumes)
    panels = load_forecast_panels(config.foundation_forecasts, config.deep_forecasts, tickers)
    panel, base_ensemble, _ = build_stack_panel(panels, features, config.start, config.end)

    errors: dict[str, str] = {}
    ridge_raw, ridge_raw_training = walk_forward_stacker(
        panel, "ridge", "target", config.min_train_months, config.ridge_alpha, config.lightgbm_rounds
    )
    ridge_excess, ridge_excess_training = walk_forward_stacker(
        panel, "ridge", "target_excess", config.min_train_months, config.ridge_alpha, config.lightgbm_rounds
    )
    try:
        lightgbm_raw, lightgbm_raw_training = walk_forward_stacker(
            panel, "lightgbm", "target", config.min_train_months, config.ridge_alpha, config.lightgbm_rounds
        )
        lightgbm_excess, lightgbm_excess_training = walk_forward_stacker(
            panel, "lightgbm", "target_excess", config.min_train_months, config.ridge_alpha, config.lightgbm_rounds
        )
    except RuntimeError as exc:
        errors["lightgbm"] = str(exc)
        empty = pd.DataFrame(index=panel["signal_date"].drop_duplicates().sort_values(), columns=sorted(panel["ticker"].unique()), dtype=float)
        lightgbm_raw = empty.copy()
        lightgbm_excess = empty.copy()
        lightgbm_raw_training = pd.Series(index=empty.index, dtype=float)
        lightgbm_excess_training = pd.Series(index=empty.index, dtype=float)

    prediction_panels: dict[str, pd.DataFrame] = {
        "existing_composite": panels["existing_composite"].reindex(index=panel["signal_date"].drop_duplicates().sort_values()),
        "forecast_rank_ensemble": base_ensemble,
        "stack_ridge_raw": ridge_raw,
        "stack_ridge_excess": ridge_excess,
    }
    if not lightgbm_raw.notna().any().any():
        errors.setdefault("stack_lightgbm_raw", errors.get("lightgbm", "no LightGBM forecasts"))
        errors.setdefault("stack_lightgbm_excess", errors.get("lightgbm", "no LightGBM forecasts"))
    else:
        prediction_panels["stack_lightgbm_raw"] = lightgbm_raw
        prediction_panels["stack_lightgbm_excess"] = lightgbm_excess
    prediction_panels["stack_ridge_lgbm_50"] = rank_blend(ridge_raw, lightgbm_raw)
    prediction_panels["stack_base_ridge_50"] = rank_blend(base_ensemble, ridge_raw)

    primary_stack_names = (
        "stack_ridge_raw",
        "stack_ridge_excess",
        "stack_lightgbm_raw",
        "stack_lightgbm_excess",
    )
    active_starts = [
        start
        for name in primary_stack_names
        if name in prediction_panels and (start := _active_start(prediction_panels[name])) is not None
    ]
    evaluation_start = min(active_starts) if active_starts else pd.Timestamp(config.start)
    evaluation_features = _slice_features(features, str(evaluation_start.date()), config.end)
    prediction_panels = {
        name: predictions.loc[predictions.index >= evaluation_start]
        for name, predictions in prediction_panels.items()
    }
    simulations: dict[str, pd.DataFrame] = {}
    metrics: dict[str, dict[str, dict[str, Any]]] = {}
    for name, predictions in prediction_panels.items():
        simulation = ml_research.simulate_predictions(
            predictions,
            evaluation_features,
            config.top_k,
            config.cost_bps,
        )
        simulations[name] = simulation
        metrics[name] = _metrics(simulation, config)

    training_rows = pd.DataFrame(
        [
            {
                "model": model,
                "target": target,
                "signals": int(predictions.notna().any(axis=1).sum()),
                "forecast_rows": int(predictions.notna().sum().sum()),
                "median_training_rows": float(training.dropna().median()) if not training.dropna().empty else np.nan,
            }
            for model, target, predictions, training in (
                ("stack_ridge_raw", "target", ridge_raw, ridge_raw_training),
                ("stack_ridge_excess", "target_excess", ridge_excess, ridge_excess_training),
                ("stack_lightgbm_raw", "target", lightgbm_raw, lightgbm_raw_training),
                ("stack_lightgbm_excess", "target_excess", lightgbm_excess, lightgbm_excess_training),
            )
        ]
    )
    write_report(
        config,
        panels,
        prediction_panels,
        simulations,
        metrics,
        training_rows,
        errors,
        evaluation_features,
    )
    return metrics


def main() -> None:
    args = parse_args()
    if args.status:
        print(json.dumps(package_status(), indent=2))
        return
    config = StackConfig(
        price_field=args.price_field,
        start=args.start,
        end=args.end,
        top_k=args.top_k,
        cost_bps=args.cost_bps,
        min_train_months=args.min_train_months,
        ridge_alpha=args.ridge_alpha,
        lightgbm_rounds=args.lightgbm_rounds,
        foundation_forecasts=args.foundation_forecasts,
        deep_forecasts=args.deep_forecasts,
    )
    metrics = run(config)
    summary = pd.DataFrame(
        [
            {
                "model": model,
                "validation_excess_cagr": values.get("validation_2022_2023", {}).get("excess_cagr"),
                "validation_sharpe": values.get("validation_2022_2023", {}).get("strategy_sharpe_rf0"),
                "holdout_2024_excess_cagr": values.get("holdout_2024", {}).get("excess_cagr"),
                "holdout_2025_2026_excess_cagr": values.get("holdout_2025_2026", {}).get("excess_cagr"),
            }
            for model, values in metrics.items()
        ]
    )
    print(summary.to_string(index=False, float_format=lambda value: f"{value:0.4f}"))
    print("\nWrote reports/stacked_model_findings.md and reports/stacked_model_metrics.csv")


if __name__ == "__main__":
    main()
